/**
 * AgencyOS — Permission catalogue
 * Stable permission keys, mirroring the AgencyOS build contract §7.3.
 */

export const PERMISSIONS = [
  "workspace.read",
  "workspace.update",
  "workspace.delete",
  "members.read",
  "members.invite",
  "members.update",
  "members.remove",
  "roles.read",
  "roles.manage",
  "teams.read",
  "teams.manage",
  "audit.read",
  "crm.read",
  "crm.create",
  "crm.update",
  "crm.delete",
  "crm.export",
  "clients.read",
  "clients.create",
  "clients.update",
  "clients.delete",
  "projects.read",
  "projects.create",
  "projects.update",
  "projects.delete",
  "tasks.read",
  "tasks.create",
  "tasks.update",
  "tasks.delete",
  "tasks.assign",
  "campaigns.read",
  "campaigns.manage",
  "content.read",
  "content.manage",
  "files.read",
  "files.upload",
  "files.delete",
  "comments.read",
  "comments.create",
  "comments.moderate",
  "approvals.read",
  "approvals.request",
  "approvals.decide",
  "time.read_own",
  "time.manage_own",
  "time.read_all",
  "time.approve",
  "finance.read",
  "finance.manage",
  "finance.export",
  "reports.read",
  "reports.create",
  "reports.share",
  "automations.read",
  "automations.manage",
  "settings.read",
  "settings.manage",
  "integrations.read",
  "integrations.manage",
  "portal.manage",
  "exports.create",
] as const

export type Permission = (typeof PERMISSIONS)[number]

/**
 * Default role → permission map.
 * Owner is implicitly granted every permission.
 */
export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  Owner: PERMISSIONS as unknown as Permission[],
  Administrator: PERMISSIONS.filter((p) => p !== "workspace.delete") as Permission[],
  Operations: [
    "workspace.read",
    "members.read",
    "roles.read",
    "teams.read",
    "audit.read",
    "crm.read",
    "clients.read",
    "clients.update",
    "projects.read",
    "projects.create",
    "projects.update",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "campaigns.read",
    "campaigns.manage",
    "content.read",
    "content.manage",
    "files.read",
    "files.upload",
    "comments.read",
    "comments.create",
    "approvals.read",
    "approvals.request",
    "time.read_all",
    "time.approve",
    "finance.read",
    "reports.read",
    "reports.create",
    "settings.read",
  ],
  Sales: [
    "workspace.read",
    "members.read",
    "crm.read",
    "crm.create",
    "crm.update",
    "crm.export",
    "clients.read",
    "clients.create",
    "projects.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "files.read",
    "files.upload",
    "comments.read",
    "comments.create",
    "approvals.read",
    "approvals.request",
    "time.read_own",
    "time.manage_own",
    "reports.read",
  ],
  "Account Manager": [
    "workspace.read",
    "members.read",
    "crm.read",
    "crm.update",
    "clients.read",
    "clients.create",
    "clients.update",
    "projects.read",
    "projects.create",
    "projects.update",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "campaigns.read",
    "content.read",
    "files.read",
    "files.upload",
    "comments.read",
    "comments.create",
    "approvals.read",
    "approvals.request",
    "approvals.decide",
    "time.read_own",
    "time.manage_own",
    "finance.read",
    "reports.read",
    "reports.share",
  ],
  "Team Member": [
    "workspace.read",
    "members.read",
    "crm.read",
    "clients.read",
    "projects.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "campaigns.read",
    "content.read",
    "content.manage",
    "files.read",
    "files.upload",
    "comments.read",
    "comments.create",
    "approvals.read",
    "approvals.request",
    "time.read_own",
    "time.manage_own",
    "reports.read",
  ],
  Contractor: [
    "workspace.read",
    "projects.read",
    "tasks.read",
    "tasks.update",
    "files.read",
    "files.upload",
    "comments.read",
    "comments.create",
    "approvals.read",
    "time.read_own",
    "time.manage_own",
  ],
  Finance: [
    "workspace.read",
    "members.read",
    "clients.read",
    "projects.read",
    "finance.read",
    "finance.manage",
    "finance.export",
    "reports.read",
    "reports.create",
    "audit.read",
  ],
  Client: [
    "workspace.read",
    "files.read",
    "comments.read",
    "comments.create",
    "approvals.read",
    "approvals.decide",
  ],
  "Guest Reviewer": [
    "approvals.read",
    "approvals.decide",
    "files.read",
    "comments.read",
    "comments.create",
  ],
}

export const SYSTEM_ROLES = Object.keys(ROLE_PERMISSIONS)

export function isSystemRole(name: string): boolean {
  return SYSTEM_ROLES.includes(name)
}
